name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]   # ← change if your default branch isn't main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # match your project’s target

      - name: Publish (Release)
        run: dotnet publish -c Release -o build

      - name: Prepare site (404 + .nojekyll + ensure base href)
        run: |
          SITE_DIR="build/wwwroot"
          test -d "$SITE_DIR"

          # 1) SPA fallback
          cp "$SITE_DIR/index.html" "$SITE_DIR/404.html"

          # 2) Disable Jekyll
          touch "$SITE_DIR/.nojekyll"

          # 3) Force <base href> to /<repo>/ no matter what it was
          REPO="${{ github.event.repository.name }}"
          INDEX="$SITE_DIR/index.html"

          # Replace ANY <base href="..."> (handles /, /foo/, missing space before />)
          sed -i -E 's|<base href="[^"]*"\s*/?>|<base href="/'"$REPO"'/"/>|g' "$INDEX"
            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
